server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.108.128
    virtual-host: /ego
    username: ego
    password: ego
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ego:
  sms:
    accessKeyId: LTAI4FkQcHbBcExV6Xp8Rpzj
    accessKeySecret: uzklCX57Tzdv54dbrZOlhvs6BS9Q2b
    signName: 易购商城
    verifyCodeTemplate: SMS_173476358


